#!/usr/bin/env python3

"""
Data acquisition GUI.
It manages configurations and launch data acquisition.
"""

import os
import sys
import logging
import logging.handlers
import tkinter as tk
from tkinter import ttk
import multiprocessing
from multiprocessing import Process, Pipe
from abc import ABC, abstractmethod
from enum import Enum
from ut61xp_get import _main

log = logging.getLogger('APP')

module_dir = os.path.dirname(os.path.abspath(__file__))
log_queue = None

DEF_FNAME        = 'data/%Y-%m-%d/%H%M%S-${MODEL}.dat'
DEF_ALT_FNAME    = 'data/%Y-%m-%d/%H%M%S-${MODEL}_.dat'
TEXT_ENTRY_WIDTH = len(DEF_ALT_FNAME)

class LauncherEvent(Enum):
    Created       = 0
    Changed       = 1
    Starting      = 2
    Started       = 3
    StartFailed   = 4
    Terminating   = 5

class Setting(ABC):
    """The base class for every launcher setting"""
    @abstractmethod
    def notify(self, event):
        """
        The following event notifications must/may be handled:
          - on LauncherState.Created the instance must initialize itself with defaults and place its controls on the launcher window;
            the particular implementation may do it in constructor instead of event handler
          - on LauncherState.Changed the instance must call launcher's get_config and update its settings accordingly
          - on LauncherState.Started the instance may call launcher's get_started_options and update its settings accordingly
          - on LauncherState.Terminating the instance may save its configuration
        """
        pass

    @abstractmethod
    def get_opts(self):
        """
        Get list of strings that should be passed to child process as arguments to its main function.
        The particular implementation may return None if current settings are invalid.
        """
        return None

    @abstractmethod
    def get_config(self):
        """Returns its own configuration as dictionary"""
        return {}

class ModelSelector(Setting):
    def __init__(self, launcher):
        self.launcher = launcher

    def notify(self, event):
        pass

    def get_opts(self):
        return ['-B', '-M', 'OWON', 'data', '-g']

    def get_config(self):
        return {}

class CheckOption(Setting):
    def __init__(self, launcher, option, text):
        self.launcher = launcher
        self.opt = option
        self.key = option.replace('-', '_')
        self.checked = tk.BooleanVar(value=False)
        control = ttk.Checkbutton(launcher.settings_frame, text=text, variable=self.checked)
        launcher.pack_control(control, 0, 2)

    def get_opts(self):
        return [] if not self.checked.get() else ['--' + self.opt]

    def get_config(self):
        return {self.key : self.checked.get()}

    def notify(self, event):
        if event == LauncherEvent.Changed:
            self.checked.set(self.launcher.get_config()[self.key])

class FileNameOption(Setting):
    def __init__(self, launcher, option, defval, text, actual_text):
        self.launcher = launcher
        self.opt = option
        self.key = option.replace('-', '_')
        self.val = tk.StringVar(value=defval)
        self.aval = tk.StringVar()
        self.create_controls(text, actual_text)

    def create_controls(self, text, actual_text):
        label = ttk.Label(self.launcher.settings_frame, text=text)
        self.launcher.pack_control(label, 0)
        entry = ttk.Entry(self.launcher.settings_frame, textvariable=self.val, width=TEXT_ENTRY_WIDTH, font='TkFixedFont')
        self.launcher.pack_control(entry, 1)
        alabel = ttk.Label(self.launcher.settings_frame, text=actual_text)
        self.launcher.pack_control(alabel, 0)
        aentry = ttk.Entry(self.launcher.settings_frame, textvariable=self.aval, width=TEXT_ENTRY_WIDTH, font='TkFixedFont', state='readonly')
        self.launcher.pack_control(aentry, 1)

    def get_config(self):
        return {self.key : self.val.get()}

    def get_opts(self):
        fname = self.val.get()
        if not fname:
            self.launcher.show_warning('filename can not be empty with --' + self.opt)
            return None
        return ['--' + self.opt, fname]

    def notify(self, event):
        if event == LauncherEvent.Changed:
            self.val.set(self.launcher.get_config()[self.key])
            self.aval.set('')
        elif event == LauncherEvent.Starting:
            self.aval.set('')
        elif event == LauncherEvent.Started:
            val = self.launcher.get_started_opts()['_' + self.key]
            self.aval.set(val if val else '')

class FileNameOptionWithChkbox(FileNameOption):
    def create_controls(self, text, actual_text):
        self.checked = tk.BooleanVar(value=False)
        label = ttk.Checkbutton(self.launcher.settings_frame, text=text, variable=self.checked, command=self.on_enable)
        self.launcher.pack_control(label, 0)
        self.entry = ttk.Entry(self.launcher.settings_frame, textvariable=self.val, width=TEXT_ENTRY_WIDTH, font='TkFixedFont', state='readonly')
        self.launcher.pack_control(self.entry, 1)
        alabel = ttk.Label(self.launcher.settings_frame, text=actual_text)
        self.launcher.pack_control(alabel, 0)
        aentry = ttk.Entry(self.launcher.settings_frame, textvariable=self.aval, width=TEXT_ENTRY_WIDTH, font='TkFixedFont', state='readonly')
        self.launcher.pack_control(aentry, 1)

    def on_enable(self):
        self.entry.config(state='normal' if self.checked.get() else 'readonly')

    def get_config(self):
        return {self.key : self.val.get(), self.key + '_en' : self.checked.get()}

    def get_opts(self):
        if not self.checked.get():
            return []
        return super().get_opts()

    def notify(self, event):
        if event == LauncherEvent.Changed:
            self.checked.set(self.launcher.get_config()[self.key + '_en'])
            self.on_enable()
        super().notify(event)

class Launcher:
    def __init__(self):
        self.root = tk.Tk()
        self.root.title('Data acquisition launcher')
        self.root.iconphoto(True, tk.PhotoImage(file=module_dir + '/meter.png'))
        self.cur_row = -1
        self.conn = None
        self.curr_evt = None
        self.cfg = None
        self.cfg_ = None
        self.started_opts = None

        self.settings_frame = tk.Frame(self.root)
        self.settings_frame.pack(side=tk.TOP)

        btn = ttk.Button(self.root, text='Start', command=self.on_start_bt)
        btn.pack(side=tk.TOP, pady=15)

        self.status_label = tk.Label(self.root,
                bd=1, relief=tk.SUNKEN, anchor=tk.W, padx=10
            )
        self.status_label.pack(side=tk.BOTTOM, fill=tk.X)
        self.create_settings()

    def create_settings(self):
        self.settings = [
            ModelSelector(self),
            CheckOption(self, 'epoch',
                'use epoch timestamps'),
            CheckOption(self, 'with-zero',
                'make sure the zero is within data graph vertical axis range (press z to toggle)'),
            CheckOption(self, 'plot-stat',
                'show statistic while plotting data (press t to toggle)'),
            CheckOption(self, 'full-screen',
                'display the graph on the entire screen (use dbl-click to toggle)'),
            CheckOption(self, 'keep-nan',
                'keep invalid data values (NaN) resulting from overload'),
            FileNameOption(self, 'file', DEF_FNAME,
                'output filename or filename template', 'actual output filename'),
            FileNameOptionWithChkbox(self, 'alt-file', DEF_ALT_FNAME,
                'alternative channel output filename or template', 'actual alternative channel output filename'),
        ]

    def on_start_bt(self):
        if self.conn is not None:
            return
        opts = self.collect_opts()
        if opts is None:
            return
        self.notify(LauncherEvent.Starting)
        self.conn, child_conn = Pipe()
        proc = Process(target=_main, args=(
                child_conn, opts, log_queue
            ), daemon=True)
        proc.start()

    def pack_control(self, ctl, col, cspan=1, sticky='w'):
        if not col:
            self.cur_row += 1
        ctl.grid(row=self.cur_row, column=col, padx=10, pady=3, columnspan=cspan, sticky=sticky)

    def show_status(self, status_str, color='darkgreen'):
        log.debug('show_status: %s', status_str)
        self.status_label.config(text=status_str, fg=color)

    def show_warning(self, msg):
        self.show_status(msg, color='darkred')

    def update_status(self, event):
        if event in (LauncherEvent.Created, LauncherEvent.Started):
            self.show_status('ready')
        elif event == LauncherEvent.Starting:
            self.show_status('starting...', color='grey')
        elif event == LauncherEvent.StartFailed:
            self.show_status('start failed', color='darkred')

    def notify(self, event):
        log.debug('notify: %s', event)
        assert self.curr_evt is None
        assert self.cfg_ is None
        self.curr_evt = event
        for se in self.settings:
            se.notify(event)
        self.curr_evt = None
        if self.cfg_ is not None:
            cfg, self.cfg_ = self.cfg_, None
            self.set_config_(cfg)
            assert self.cfg_ is None
        self.update_status(event)

    def set_config(self, cfg):
        log.debug('set_config: %s', cfg)
        if self.curr_evt is None:
            self.set_config_(cfg)
        else:
            assert self.cfg_ is None
            self.cfg_ = cfg

    def set_config_(self, cfg):
        self.cfg = cfg
        self.notify(LauncherEvent.Changed)

    def get_config(self):
        return self.cfg

    def collect_config(self):
        cfg = {}
        for se in self.settings:
            cfg = {**cfg, **se.get_config()}
        log.debug('collect_config: %s', cfg)
        return cfg

    def collect_opts(self):
        opts = []
        for se in self.settings:
            se_opts = se.get_opts()
            if se_opts is None:
                opts = None
                break
            opts += se_opts
        log.debug('collect_opts: %s', opts)
        return opts

    def get_started_opts(self):
        return self.started_opts

    def detach_child(self):
        self.conn.close()
        self.conn = None

    def idle_work(self):
        self.root.after(50, self.idle_work)
        self.do_idle()

    def do_idle(self):
        if not self.conn:
            return
        try:
            if not self.conn.poll(0):
                return
            opts = self.conn.recv()
            log.debug('started with opts=%s', opts)
            self.started_opts = opts
            self.notify(LauncherEvent.Started)
        except (BrokenPipeError, EOFError):
            self.notify(LauncherEvent.StartFailed)
        self.detach_child()

    def run(self):
        self.notify(LauncherEvent.Created)
        self.root.after_idle(self.idle_work)
        self.root.mainloop()
        self.notify(LauncherEvent.Terminating)

def mkdir_safe(path):
    try:
        os.mkdir(path)
    except:
        pass

if __name__ == '__main__':
    multiprocessing.freeze_support()
    multiprocessing.set_start_method('spawn')
    current_dir = module_dir
    if frozen := getattr(sys, 'frozen', False):
        current_dir += '/..'
    os.chdir(current_dir)
    mkdir_safe('.logs')
    mkdir_safe('.cfg')
    mkdir_safe('data')
    if frozen:
        sys.stdout = sys.stderr = open('.logs/launcher_out.log', 'w', encoding='utf-8')
    logging.basicConfig(
        format='%(asctime)s %(message)s',
        level=logging.DEBUG, handlers=[
            logging.handlers.RotatingFileHandler('.logs/launcher.log', 'a', 128*1024, 2)
        ])
    if frozen:
        log_queue = multiprocessing.Manager().Queue()
        file_handler = logging.handlers.RotatingFileHandler('.logs/dmm.log', 'a', 128*1024, 2)
        file_handler.setFormatter(logging.Formatter('%(asctime)s %(name)s %(message)s'))
        listener = logging.handlers.QueueListener(log_queue, file_handler)
        listener.start()

    Launcher().run()

    if frozen:
        listener.stop()
